# Generated by Django 4.1.7 on 2023-02-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, verbose_name='User Id')),
                ('section', models.CharField(max_length=50, verbose_name='Section')),
                ('page', models.CharField(max_length=50, verbose_name='Page')),
                ('data', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='userLogin',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('userid', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('pswd', models.CharField(max_length=30)),
            ],
        ),
    ]
