# Generated by Django 4.1 on 2023-02-23 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterTable',
            fields=[
                ('userdataid', models.IntegerField(primary_key='True', serialize=False)),
                ('user', models.CharField(max_length=50, verbose_name='User Id')),
                ('section', models.CharField(max_length=50, verbose_name='Section')),
                ('page', models.CharField(max_length=50, verbose_name='Page')),
                ('data', models.CharField(max_length=500)),
            ],
        ),
    ]
