# Generated by Django 4.1.7 on 2023-03-02 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_remove_mastertable_section"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userlogin",
            name="email",
        ),
    ]
