# Generated by Django 4.1.7 on 2023-02-27 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_mastertable_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mastertable',
            name='user',
        ),
        migrations.AddField(
            model_name='mastertable',
            name='userid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.userlogin'),
        ),
    ]
