# Generated by Django 4.1.7 on 2023-03-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_userlogin_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogin',
            name='userid',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
