# Generated by Django 4.1.7 on 2023-02-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projectApp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mastertable",
            name="userdataid",
        ),
        migrations.AddField(
            model_name="mastertable",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
    ]
